# 输入密码时使用的密码掩码
# 如果是不被支持的值，则使用默认值
# 默认值: "*"
passwd_mask: "*"

# 盐的文件名，例：salt
# 注意：虽然导入时可以使用不同的密码，但是盐是相同的
# 默认值: "salt"
salt_name: "salt"

# 盐的保存位置，需为绝对路径，例：C:\Users\Nya-WSL\Fernet_dbfp
# 如果是 "cwd"，则盐将保存在程序工作目录中
# 默认值: "cwd"
salt_path: "cwd"

# 密文的文件名，不要写文件后缀，例：pem
# 默认值: "pem"
save_name: "pem"

# 密文的保存位置，需为绝对路径，例：C:\Users\Nya-WSL\Fernet_dbfp
# 如果是 "cwd"，则密文将保存在程序工作目录中
# 默认值: "cwd"
save_path: "cwd"

# 密文保存模式，可选值: "json", "sqlite3（未实现）"
# 默认值: "json"
save_mode: "json"

# PBKDF2HMAC密钥派生函数的迭代次数，必须是整数（int）
# 默认值: 480000
iterations: 480000

# 导入单个文件时是否根据文件名自动生成别称（键名），可选值: True, False
# 默认值: True
auto_import_name: True

# 是否检查更新，可选值: True, False （未实现）
update: True
